name: S3 Deploy
on:
  push:
    branches: 
    - master
    
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install -g typescript
          curl https://github.com/chartjs/Chart.js/releases/download/v4.4.2/chart.js-4.4.2.tgz
          tar -xzf chart.js-4.4.2.tgz


      - name: Compile typescript
        run: tsc --module es2022 data_processing.ts 

      - name: Copy files
        run: |
          mkdir output
          cp -r chartjs output/
          cp index.html output/
          cp data_processing.js output/
          cp original_data.js output/

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: output
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          delete-removed: true
          no-cache: true